version: '2'
services:
  influxdb:
    image: arm32v7/influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    restart: unless-stopped
  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    ports:
      - '8081:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
    restart: unless-stopped
  flask:
    build: ./flask-config-roompi
    ports:
      - '8082:8082'
    volumes:
      - /home/pi/roompi.conf:/app/roompi.conf
    restart: unless-stopped
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage: